package mybatis.mapper;

import java.util.List;
import mybatis.pojo.Dept;
import mybatis.pojo.DeptExample;
import org.apache.ibatis.annotations.Param;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Wed Sep 14 14:41:17 GMT+08:00 2022
     */
    int countByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Wed Sep 14 14:41:17 GMT+08:00 2022
     */
    int deleteByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Wed Sep 14 14:41:17 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Integer departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Wed Sep 14 14:41:17 GMT+08:00 2022
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Wed Sep 14 14:41:17 GMT+08:00 2022
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Wed Sep 14 14:41:17 GMT+08:00 2022
     */
    List<Dept> selectByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Wed Sep 14 14:41:17 GMT+08:00 2022
     */
    Dept selectByPrimaryKey(Integer departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Wed Sep 14 14:41:17 GMT+08:00 2022
     */
    int updateByExampleSelective(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Wed Sep 14 14:41:17 GMT+08:00 2022
     */
    int updateByExample(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Wed Sep 14 14:41:17 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated Wed Sep 14 14:41:17 GMT+08:00 2022
     */
    int updateByPrimaryKey(Dept record);
}